print('Welcome to the Mad Lib Generator')

adjective_1 = raw_input('Type in an adjective: ')
adjective_2 = raw_input('Another adjective: ')
adjective_3 = raw_input('And another adjective: ')
adjective_4 = raw_input('One more adjective: ')
plural_animal = raw_input('Plural animal (e.g., cats): ')
verb = raw_input('Now a verb: ')
plural_noun = raw_input('Now a plural noun: ')
woman = raw_input('The first name of a woman musician: ')
beverage = raw_input('A beverage: ')
body_part = raw_input('And finally, a plural body part: ')

print(' ')
print("Excellent choices! Here's your story...")
print('-----------------------------------')
print("There once was a " + adjective_1 + " programmer named " + woman + " who wanted to build a " +  adjective_2 + " mobile app to help " + adjective_3 + " " + plural_animal + " find new homes. ")
print(woman + " stayed up all night, drinking lots of caffeinated " + beverage + " as she worked and worked trying to complete her " + adjective_4 + " program. ")
print("Whenever " + woman + " hit a dead end, she would exclaim *" + plural_noun + "*! ")
print("But she was not discouraged, and after a quick break to " + verb + " and clear her head, she got back to work. ")
print("By morning, when the sun started to rise, she let out a big yawn and stretched her " + body_part + ". Finally, she was done.")
print('-------------------------------------')